services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fortega21/olha-mensagem-app:latest
    container_name: olha-mensagem-app
    environment:
      PORT: 8080
      DB_NAME: /olha-mensagem-app/data/olha_mensagem.db
      DB_MIGRATIONS_PATH: /olha-mensagem-app/internal/database/migrations
      LOG_LEVEL: INFO
    volumes:
      - olha-mensagem-db-data:/olha-mensagem-app/data
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  olha-mensagem-db-data:

networks:
  app-network:
    driver: bridge
