services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fortega21/olha-mensagem-app:latest
    container_name: olha-mensagem-app
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    environment:
      PORT: 8080
      DB_NAME: /olha-mensagem-app/data/olha_mensagem.db
      DB_MIGRATIONS_PATH: /olha-mensagem-app/internal/database/migrations
      LOG_LEVEL: INFO
      MESSAGES_LIMIT: 150
    volumes:
      - olha-mensagem-db-data:/olha-mensagem-app/data
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: fortega21/olha-mensagem-nginx:latest
    container_name: nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  olha-mensagem-db-data:

networks:
  app-network:
    driver: bridge
