services:
  olha-mensagem:
    build:
      context: .
      dockerfile: Dockerfile
    image: fortega21/olha-mensagem-app:latest
    container_name: olha-mensagem-app
    environment:
      PORT: 8080
      DB_NAME: /app/data/olha_mensagem.db
      DB_MIGRATIONS_PATH: /app/internal/database/migrations
    volumes:
      - olha-mensagem-db-data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  olha-mensagem-db-data:
