// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel.sql

package repository

import (
	"context"
	"database/sql"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, description, created_by)
VALUES (?, ?, ?)
RETURNING id, name, description, created_by, created_at
`

type CreateChannelParams struct {
	Name        string
	Description sql.NullString
	CreatedBy   int64
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.queryRow(ctx, q.createChannelStmt, createChannel, arg.Name, arg.Description, arg.CreatedBy)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
WHERE id = ? AND created_by = ?
`

type DeleteChannelParams struct {
	ID        int64
	CreatedBy int64
}

func (q *Queries) DeleteChannel(ctx context.Context, arg DeleteChannelParams) error {
	_, err := q.exec(ctx, q.deleteChannelStmt, deleteChannel, arg.ID, arg.CreatedBy)
	return err
}

const getAllChannels = `-- name: GetAllChannels :many
SELECT id, name, description, created_by, created_at
FROM channels
ORDER BY created_at DESC
`

func (q *Queries) GetAllChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.query(ctx, q.getAllChannelsStmt, getAllChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, description, created_by, created_at
FROM channels
WHERE id = ?
`

func (q *Queries) GetChannelByID(ctx context.Context, id int64) (Channel, error) {
	row := q.queryRow(ctx, q.getChannelByIDStmt, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
