// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Channel struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedBy   int64
	CreatedAt   time.Time
}

type User struct {
	ID        int64
	Username  string
	Password  string
	CreatedAt time.Time
}
