name: Deploy Application

on:
  workflow_run:
    workflows: ["Build & Push"]
    types:
      - completed
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Deploy Application
      run: |
        cd ${{ secrets.OLHA_MENSAGEM_DIRECTORY_VM }}
        docker compose pull
        docker compose up -d