name: Deploy Application

on:
  workflow_run:
    workflows: ["Build & Push"]
    types:
      - completed
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Update docker-compose
      run: |
        cp ${{ github.workspace }}/docker-compose.yml ${{ secrets.OLHA_MENSAGEM_DIRECTORY_VM }}/docker-compose.yml
    - name: Run docker-compose
      run: |
        cd ${{ secrets.OLHA_MENSAGEM_DIRECTORY_VM }}
        docker compose pull
        docker compose up -d