name: Go Tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'
    
    - name: Run tests
      run: go test -v ./...